version: '3'
services:
  mysql:
    image: mariadb:10.5.9
    logging:
      driver: none
    env_file:
      - .env
    command: --max_allowed_packet=512M
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - ols_vpc
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    logging:
      driver: none
    env_file:
      - .env
    volumes:
      - ./lsws/php/php.ini:/usr/local/lsws/lsphp81/etc/php/8.1/litespeed/php.ini
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wpx.rule=Host(`domain.com`)" #Type your domain here
      - "traefik.http.routers.wpx.entrypoints=websecure"
      - "traefik.http.services.wpx.loadbalancer.server.port=80"
      - "traefik.http.routers.wpx.service=wpx"
      - "traefik.http.routers.wpx.tls.certresolver=leresolver"
      - "traefik.http.routers.olsx.rule=Host(`litespeed.domain.com`)" #Type your domain here
      - "traefik.http.routers.olsx.entrypoints=websecure"
      - "traefik.http.services.olsx.loadbalancer.server.port=7080"
      - "traefik.http.routers.olsx.service=olsx"
      - "traefik.http.routers.olsx.tls.certresolver=leresolver"
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - ols_vpc
      - traefik_vpc

networks:
  ols_vpc:
    driver: bridge
  traefik_vpc:
    external: true
